image: runmymind/docker-android-sdk:latest

stages:
  - build
  - test
  - package

####################################################################################################
# BUILD
####################################################################################################
before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle


cache:
  key: $CI_PROJECT_NAME
  paths:
    - .gradle/
    - .gradle/wrapper/
    - .gradle/caches/
    - build/


.build_template: &build_template_def
  stage: build
  artifacts:
    expire_in: 2 days
    paths:
      - app/build/outputs/
      - .android/
      - ./deliverables

build_debug:
  <<: *build_template_def
  only:
    - master
  script:
    - ./gradlew assembleDebug  --no-daemon
    - ./gradlew sonarqube 

#build_release:
#  <<: *build_template_def
#  only:
#    - production
#  script:
#    - ./gradlew assembleRelease  --no-daemon

####################################################################################################
# PACKAGE APK FOR DOWNLOADING


.package_template: &package_template_def
  before_script:
    - export VERSION_NAME=`egrep '^[[:blank:]]+versionName[[:blank:]]'  app/build.gradle | awk '{print $2}' | sed s/\"//g`
    - export VERSION_CODE=`egrep '^[[:blank:]]+versionCode[[:blank:]]'  app/build.gradle | awk '{print $2}'`
    - mkdir -p deliverables

    # Store some information about the build
    - touch ./deliverables/info.txt
    - echo "Build date          $(date)"                >> ./deliverables/info.txt
    - echo "App version name    ${VERSION_NAME}"        >> ./deliverables/info.txt
    - echo "App version code    ${VERSION_CODE}"        >> ./deliverables/info.txt
    - echo "Git branch          ${CI_COMMIT_REF_NAME}"  >> ./deliverables/info.txt
    - echo "Git commit          ${CI_COMMIT_SHA}"       >> ./deliverables/info.txt
    - echo "Gitlab pipeline     ${CI_PIPELINE_ID}"      >> ./deliverables/info.txt


package_develop:
  <<: *package_template_def
  stage: package
  environment: Development
  only:
    - production
  script:
    - mv app/build/outputs/apk/app-debug.apk ./deliverables/NameOfTheApp-v$VERSION_NAME-$VERSION_CODE-debug.apk
  artifacts:
    expire_in: 3 days
    paths:
    - deliverables

package_release:
  <<: *package_template_def
  stage: package
  environment: Release
  only:
    - production
  script:
    - mv app/build/outputs/apk/app-release.apk ./deliverables/NameOfTheApp-v$VERSION_NAME-$VERSION_CODE-release.apk
  artifacts:
    expire_in: 4 weeks
    paths:
    - deliverables
