package com.gdt.speedtest.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gdt.speedtest.database.Result;

import com.gdt.speedtest.database.ResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig resultDaoConfig;

    private final ResultDao resultDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        resultDaoConfig = daoConfigMap.get(ResultDao.class).clone();
        resultDaoConfig.initIdentityScope(type);

        resultDao = new ResultDao(resultDaoConfig, this);

        registerDao(Result.class, resultDao);
    }
    
    public void clear() {
        resultDaoConfig.clearIdentityScope();
    }

    public ResultDao getResultDao() {
        return resultDao;
    }

}
